name: security-aspects

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  oidctest:
    runs-on: ubuntu-latest

    steps:
      - name: Debug OIDC claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: sts.amazonaws.com

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Check AWS Access
        run: |
          aws sts get-caller-identity
